product_dashboard:
  path: /dashboard
  controller: App\Controller\ProductDashboardController::index

product_add:
  path: /product/add
  controller: App\Controller\ProductAddController::index

product_list:
  path: /product/list
  controller: App\Controller\ProductListController::index
app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register